cat > buildspec.yml << 'EOF'
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      # Install Python dependencies in the current directory
      - pip install -r requirements.txt -t .
      # Package everything including dependencies
      - aws cloudformation package --template-file search-function.yaml --s3-bucket artifacts-bucket-gl --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yaml
    - '**/*'
EOF
